services:
  api-botones:
    build: .
    container_name: api_botones_contenedor
    ports:
      - "3000:80"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:      
      - MONGO_URL=mongodb://mongodb:27017/

  mongodb:
    image: mongo:latest
    container_name: mongodb_botones
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
